#spring:
#  application:
#    name: car-service
#
#  # COSMOS DB Configuration
#  data:
#    mongodb:
#      uri: ${MONGO_URI}
#  # H2 Database Configuration (commented out)
##  datasource:
##    url: jdbc:h2:mem:orderdb
##    driver-class-name: org.h2.Driver
##    username: sa
##    password: password
##
##  # JPA/Hibernate Configuration
##  jpa:
##    database-platform: org.hibernate.dialect.H2Dialect
##    hibernate:
##      ddl-auto: create-drop
##    show-sql: true
##    properties:
##      hibernate:
##        format_sql: true
##
##  # H2 Console (for testing)
##  h2:
##    console:
##      enabled: true
##      path: /h2-console
